### ISSUE TITLE
Still working ?

### ISSUE THREAD

**Issue by NZTSL** [narbehaj/telegram-audio-download#3]
Hi,

Does this script still work ? 
Nothing is happening when I run it.

Thanks.

**Comment by narbehaj** [comment]
Hi, I guess not, I might say this has been deprecated since it uses old API methods.

**Comment by NZTSL** [comment]
Thanks for your answer.

Do you know any equivalent by chance ?

**Comment by narbehaj** [comment]
I haven't seen such thing. But I can take a look again.

-------- Original Message --------

**Comment by NZTSL** [comment]
I managed to do something with the pyrogram lib.
Thanks.
